"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const noname_1 = require("./noname");
exports.default = noname_1.default;
var noname_anotations_1 = require("./noname.anotations");
exports.router = noname_anotations_1.router;
exports.get = noname_anotations_1.get;
exports.post = noname_anotations_1.post;
exports.put = noname_anotations_1.put;
exports.patch = noname_anotations_1.patch;
exports.del = noname_anotations_1.del;
