export const NONAME_TYPE = 'NONAME_TYPE';
export const NONAME_TYPE_ROUTER = 'NONAME_TYPE_ROUTER';
export const NONAME_TYPE_SERVICE = 'NONAME_TYPE_SERVICE';
export const NONAME_ROUTER_CONFIG = 'NONAME_ROUTER_CONFIG';
export const NONAME_ENDPOINTS = 'NONAME_ENDPOINTS';
export const NONAME_SYMBOL = 'NONAME_SYMBOL';
